     # Apache Configuration
- name: Create document root
  file:
    path: "{{ wordpress_directory }}"
    #path: "/var/www/{{ domain }}"
    state: directory
    owner: "{{app_user}}"
    group: "{{app_user}}"
    mode: '0755'

- name: Set up Apache VirtualHost
  template:
    src: "{{httpd_conf}}.j2"
    dest: "{{httpd_configuration_dir}}/sites-available/{{httpd_conf}}"  #wordpress_httpd_configuration: '/etc/apache2/sites-available/{{http_conf}}'
    #dest: "{{wordpress_httpd_configuration}}"  #wordpress_httpd_configuration: '/etc/apache2/sites-available/{{http_conf}}'
    #src: "files/apache.conf.j2"
    #dest: "/etc/apache2/sites-available/{{ http_conf }}"
  notify: Reload Apache
  tags: [ apache ]

- name: Enable rewrite module
  shell: /usr/sbin/a2enmod rewrite
  notify: Reload Apache
  tags: [ apache ]

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ httpd_conf.split('.')[0] }}
  notify: Reload Apache
  tags: [ apache ]

- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default
  notify: Restart Apache
  tags: [ apache ]

- name: Adding the path in the bashrc files
  lineinfile: 
    path: ~/.profile
    line: export PATH=$PATH:/usr/sbin
    state: present

- name: source bashrc file
  shell: source ~/.bashrc
  args:
     executable: /bin/bash

# UFW Configuration
- name: "UFW - Allow HTTP on port {{ http_port }}"
  ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp
  tags: [ system ]
  become: yes