- name: Download WordPress  
  get_url: 
    url: https://wordpress.org/wordpress-{{wp_version}}.tar.gz
    dest: "{{ tmp_dir }}/"
    force: no
  become: yes

- name: Extract WordPress
  become: yes
  become_method : sudo
  unarchive: 
    src: "{{ tmp_dir }}/wordpress-{{wp_version}}.tar.gz"
    dest: "{{wordpress_directory}}"
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: subtitute for rendering wp-config.php 
  template:
    src: "wp-config.php.j2"
    dest: "{{ wordpress_directory }}/wp-config.php"
  tags: [ wordpress ]

- name: Remove sample file =  {{ wordpress_directory }}/wp-config-sample.php 
  file:
    state: absent
    path: "{{ wordpress_directory }}/wp-config-sample.php"
  become: yes

## TODO : verifi wp-config-sample.php

- name: Attempt to change ownership on {{ wordpress_directory }}
  file:
    path: "{{ wordpress_directory }}"
    state: directory
    recurse: yes
    owner: "{{app_user}}"
    group: "{{app_user}}"
    mode: '0755'
  become: yes

- name: Set permissions for files into {{ wordpress_directory }} directory
  shell: "/usr/bin/find {{ wordpress_directory }} -type f -exec chmod 640 {} \\;"
  tags: [ wordpress ] 