---
- name : Installation aws wordpress platforme
  hosts: 127.0.0.1
  connection : local
  user: vagrant
  gather_facts: yes
  become: yes 
  vars_files:
    - vars/main.yml
  roles:
    - custom-wamp