---
- name : Installation aws wordpress platforme
  hosts: web 
  #ansible_python_interpreter: /usr/bin/python
  #user: admin
  remote_user: admin
  gather_facts: yes
  become: yes 
  vars_files:
    - vars/main.yml
    - vars/datasource.yml

  roles:
    - custom-wamp

# todo : pass rds-mysql addree to ansible var file :
# https://stackoverflow.com/questions/40353666/how-to-pass-terraform-outputs-variables-into-ansible-as-vars-files
# https://github.com/mantl/terraform.py